### ISSUE TITLE
StatisticMetaData: Invalid filed state_unit_of_measurement

### ISSUE THREAD

**Issue by alexz707** [DarkC35/ha_linznetz#1]
HI!
just tried your component and it failed when I try to import data.
If you just remove the line  107 of Sensor.py it works again ;)

Regards Alex

**Comment by DarkC35** [comment]
Hi thanks for your feedback!

Yeah I know but it's strange because I installed it on two instances and one required this line and the other one broke because of this line (and I manually removed it). I wanted to wait for some newer HA versions so I could determine which one of this behaviors is intended for future releases because I tested it during the time HA core changed their internal API x'D

I will try to remove this line and look how my instance behaves. 

Did you manage to set up an automation to import your reports everyday? I could provide an example in the readme if you want. ^^

**Comment by alexz707** [comment]
Yeah this change is relatively new, maybe your 2 instances had different versions installed?

Mine versions are
 Home Assistant 2022.11.3 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221108.0 - latest 

Maybe that helps to figure it out ;)

Currently I only did a manual import but I have read your post on reddit about the imap "hack"
would be awesome if you could share your example ;-)

**Comment by DarkC35** [comment]
They had different versions at first (somewhere near 2022.8.0) but I think it still happed after updating on instance to the version of the other one. But yeah I will look into it sometime.

I updated the readme with steps how I set up the "hack" and everything. It would be nice if you could give me feedback whether the documentation is helpful or if you think anything is missing  ;D.

Btw I'm surprised someone actually found this component via reddit and am glad that maybe more than 2 people are going to use it. ^^ I can assure you that I'm using it for 2 months now and it only broke once during the daylight saving change.

**Comment by DarkC35** [comment]
Tested it without the state_unit_of_measurement property on my instance (that required it previously) for two days and it didn't break anything on version 2022.11.0. I just merged a PR with a fix und hope this will prevent anyone from running into this problem ever again. ^^

Just to make sure I increades the min. required home-assistant version to 2022.10.0 and hacs to 1.28.0 as well.

**Comment by alexz707** [comment]
Your readme is fine thanks a lot but I could not get it running.
It seems that there is a problem with the mail attachment plugin.
The integration gets the info that there is a new mail but it doesn't download any file. 
(I forward the mail to circumvent the SMIME problem, so this should not be the problem)

Do you have an idea what could go wrong? Otherwise I have to debug it...

BTW: I'm wondering if the files get deleted after the import is finished ?

**Comment by DarkC35** [comment]
No the file does not get deleted after import. (So you would have an "archive" of your previous reports somewhere ;D)

Some debugging steps on the top of my head would be:
1. Check your `/config` folder of your HA installation if there is the folder you configured (in my example `attachments`), the folder has to be created manually. Also check if there are some files in the folder already (`.txt`, `.csv`, `.xml`).
2. Run `ls -la` and check if the permissions on the `attachments` folder are similar to all the other folders/files (e.g. `drwxr-xr-x root:root`)
3. Make sure you also have the `allowlist_external_dirs` configuration set in your HA configs.
4. Open HA > Developer Tools > States and search for your enity (in my example `sensor.linz_netz_attachments`) and check the value of the state (should be something like `/config/attachments/ATxxxxxxx_QH_xxxxx.csv`) Maybe you have to resend a mail to yourself with the `.csv` file attached.
5. Check your E-Mail rules.
6. Check the `folder` and `senders` property in your HA `imap_attachment` configs.
7. Check all your sensor/entity names in the developer tools if you need to adapt those in your automation.

Does a manual import work? Otherwise there is the "traces" feature in the automation settings you can use for debugging.

**Comment by DarkC35** [comment]
Okay that's another way I guess xD Just took a quick look on your changes and I'm not sure why the original code did not work on your end. Maybe an typo in the `value_template` config? You could try to debug with another sensor that uses something like `value_template: {{ attachment_paths }}` to see what happens.

I don't know much about mail formats and encryption but if you are familiar with those it would be nice to add SMIME decryption support in the upstream mail integration to get rid of my ugly workaround xD

**Comment by alexz707** [comment]
There was no typo, I did only change the sensor code.

Well I guess I have fixed it and changed the behavior a bit :D
Now it deals with the smime thing  (the attachments are not encrypted but sent as octet stream)
I changed the behavier to not look at the current date but it just looks if messages are unread and marks them as seen if the message is a valid one ;)
