### ISSUE TITLE
Funktioniert nicht!

### ISSUE THREAD

**Issue by irmscher123** [DarkC35/ha_linznetz#16]
Leider funktioniert das Plugin nicht

Es scheitert beim importieren, dass er den Ordner, wo die csv Dateinen drinnen sind, nicht findet.

ich habe eine generic version

alle versiche /www/linznetz, /config/linznetz/, etc ohne Erfolg, er findet es einfach nicht :(

Wie kann man sonst die Dateien einlesen

DAnke

**Comment by DarkC35** [comment]
Did you only pass the folder path as an argument or the full file path? Because the full file path is required, e.g.:
`/config/attachments/AT0000000000000000000000000000000_QH_20240311.csv`

It is also necessary to use the full/absolute path to the file. Since I don't know what you mean with "generic version" I assume you don't use HA OS or the docker container where your root folder for configurations is `/config` so I would recommend to locate the folder where you stored the CSV files with a command line and print the current folder with a command like `pwd`.

On Linux your absolute path could look somewhat like this:
/home/username/homeassistant/config/...

**Comment by irmscher123** [comment]
Hi the generic version of homeassistant is running on a pc not rasperry.

it was my fault.

i put the correct filepath and the script is running.

thanks
